In [66]:
import pandas as pd
import seaborn as sns
import numpy as np

In [67]:
df = pd.read_csv('../day3/imputed_mf_train.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35970 entries, 0 to 35969
Data columns (total 40 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   id      35970 non-null  int64  
 1   DC024   35970 non-null  int64  
 2   DC025   35970 non-null  int64  
 3   DC205   35970 non-null  float64
 4   DC206   35970 non-null  float64
 5   DC207   35970 non-null  float64
 6   DC208   35970 non-null  float64
 7   DC209   35970 non-null  float64
 8   DC210   35970 non-null  float64
 9   DC211   35970 non-null  float64
 10  DC212   35970 non-null  float64
 11  DC213   35970 non-null  float64
 12  DC214   35970 non-null  float64
 13  DC215   35970 non-null  float64
 14  DC216   35970 non-null  float64
 15  DC217   35970 non-null  int64  
 16  DC219   35970 non-null  int64  
 17  DC220   35970 non-null  float64
 18  DC226   35970 non-null  float64
 19  DC230a  35970 non-null  float64
 20  DC230b  35970 non-null  float64
 21  DC232   35970 non-null  float64
 22

In [68]:
df = df.drop('id', axis=1)

In [69]:
df['DC205'].unique()

array([16., 31., 12., 21., 17., 96.])

In [70]:
target = 'DC201'
NUMERICAL_DATA = ['DC216', 'DC220', 'DC142a']
CATEGORICAL_DATA = [column for column in df.columns if column != target and column not in NUMERICAL_DATA]

COLUMN_CATEGORICAL_INDEX = []

for column in CATEGORICAL_DATA:
    COLUMN_CATEGORICAL_INDEX.append(df.columns.get_loc(column))

In [71]:
df[CATEGORICAL_DATA] = df[CATEGORICAL_DATA].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35970 entries, 0 to 35969
Data columns (total 39 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   DC024   35970 non-null  category
 1   DC025   35970 non-null  category
 2   DC205   35970 non-null  category
 3   DC206   35970 non-null  category
 4   DC207   35970 non-null  category
 5   DC208   35970 non-null  category
 6   DC209   35970 non-null  category
 7   DC210   35970 non-null  category
 8   DC211   35970 non-null  category
 9   DC212   35970 non-null  category
 10  DC213   35970 non-null  category
 11  DC214   35970 non-null  category
 12  DC215   35970 non-null  category
 13  DC216   35970 non-null  float64 
 14  DC217   35970 non-null  category
 15  DC219   35970 non-null  category
 16  DC220   35970 non-null  float64 
 17  DC226   35970 non-null  category
 18  DC230a  35970 non-null  category
 19  DC230b  35970 non-null  category
 20  DC232   35970 non-null  category
 21  DC232b  3597

In [72]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# scaler = StandardScaler()

numerical_df = df[NUMERICAL_DATA].copy()
categorical_df = df[CATEGORICAL_DATA].copy()

merged_df_train = pd.concat([numerical_df, categorical_df], axis=1)
X_test_submit = np.array(merged_df_train)

merged_df_train

DC216  DC220  DC142a DC024 DC025 DC205 DC206 DC207 DC208 DC209  ...   
0        1.0   80.0    60.0    11     2  16.0   1.0   0.0   1.0   0.0  ...  \
1        2.0   44.0    70.0    11     2  31.0   1.0   0.0   1.0   0.0  ...   
2        2.0   35.0    75.0    11     2  12.0   1.0   0.0   1.0   1.0  ...   
3        3.0   79.0    85.0    11     2  12.0   1.0   0.0   0.0   0.0  ...   
4        2.0   37.0    65.0    11     2  12.0   1.0   0.0   1.0   1.0  ...   
...      ...    ...     ...   ...   ...   ...   ...   ...   ...   ...  ...   
35965    1.0   21.0     9.0    94     1  17.0   1.0   0.0   0.0   0.0  ...   
35966    1.0   41.0    12.0    94     1  12.0   1.0   0.0   1.0   1.0  ...   
35967    2.0   52.0    48.0    94     1  12.0   1.0   0.0   1.0   1.0  ...   
35968    2.0   58.0    39.0    94     1  12.0   1.0   0.0   1.0   1.0  ...   
35969    1.0   31.0    40.0    94     1  12.0   1.0   0.0   1.0   1.0  ...   

      DC237d DC237e DC237f DC241 DC242 DC244 DC246 DC252 DC270a DC109  
0        0.0    0.0    0.0   1.0   0.0   0.0   0.0   2.0      1  12.0  
1        0.0    0.0    0.0   1.0   0.0   1.0   1.0   1.0      2  31.0  
2        0.0    0.0    0.0   1.0   0.0   1.0   1.0   0.0      4  11.0  
3        0.0    0.0    0.0   2.0   1.0   1.0   0.0   1.0      1  11.0  
4        1.0    0.0    0.0   1.0   0.0   0.0   1.0   0.0      2  11.0  
...      ...    ...    ...   ...   ...   ...   ...   ...    ...   ...  
35965    0.0    0.0    0.0   3.0   0.0   0.0   0.0   0.0      1  21.0  
35966    0.0    0.0    0.0   1.0   1.0   0.0   0.0   0.0      2  11.0  
35967    0.0    0.0    0.0   1.0   1.0   0.0   1.0   1.0      1  11.0  
35968    0.0    0.0    0.0   1.0   1.0   0.0   0.0   0.0      2  11.0  
35969    0.0    0.0    0.0   1.0   0.0   0.0   0.0   0.0      3  11.0  

[35970 rows x 38 columns]

In [73]:
import sklearn
sklearn.set_config(transform_output="pandas")

In [74]:
import category_encoders
encoder = category_encoders.OrdinalEncoder()
encoded_df_train = encoder.fit_transform(merged_df_train, column=CATEGORICAL_DATA)
encoded_variables = encoder.category_mapping
# encoded_variables
encoded_df_train

DC216  DC220  DC142a  DC024  DC025  DC205  DC206  DC207  DC208  DC209   
0        1.0   80.0    60.0      1      1      1      1      1      1      1  \
1        2.0   44.0    70.0      1      1      2      1      1      1      1   
2        2.0   35.0    75.0      1      1      3      1      1      1      2   
3        3.0   79.0    85.0      1      1      3      1      1      2      1   
4        2.0   37.0    65.0      1      1      3      1      1      1      2   
...      ...    ...     ...    ...    ...    ...    ...    ...    ...    ...   
35965    1.0   21.0     9.0     34      2      5      1      1      2      1   
35966    1.0   41.0    12.0     34      2      3      1      1      1      2   
35967    2.0   52.0    48.0     34      2      3      1      1      1      2   
35968    2.0   58.0    39.0     34      2      3      1      1      1      2   
35969    1.0   31.0    40.0     34      2      3      1      1      1      2   

       ...  DC237d  DC237e  DC237f  DC241  DC242  DC244  DC246  DC252  DC270a   
0      ...       1       1       1      1      1      1      1      1       1  \
1      ...       1       1       1      1      1      2      2      2       2   
2      ...       1       1       1      1      1      2      2      3       3   
3      ...       1       1       1      2      2      2      1      2       1   
4      ...       2       1       1      1      1      1      2      3       2   
...    ...     ...     ...     ...    ...    ...    ...    ...    ...     ...   
35965  ...       1       1       1      3      1      1      1      3       1   
35966  ...       1       1       1      1      2      1      1      3       2   
35967  ...       1       1       1      1      2      1      2      2       1   
35968  ...       1       1       1      1      2      1      1      3       2   
35969  ...       1       1       1      1      1      1      1      3       5   

       DC109  
0          1  
1          2  
2          3  
3          3  
4          3  
...      ...  
35965      6  
35966      3  
35967      3  
35968      3  
35969      3  

[35970 rows x 38 columns]

In [75]:
encoded_df_train['DC024'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [76]:
merged_df_train.nunique()

DC216      15
DC220      84
DC142a    362
DC024      34
DC025       2
DC205       6
DC206       2
DC207       2
DC208       2
DC209       2
DC210       2
DC211       2
DC212       2
DC213      10
DC214      15
DC215      12
DC217       6
DC219       2
DC226      11
DC230a      5
DC230b      2
DC232       2
DC232b      2
DC235       3
DC237       3
DC237a      3
DC237b      3
DC237c      3
DC237d      3
DC237e      3
DC237f      3
DC241       4
DC242       2
DC244       2
DC246       2
DC252       5
DC270a      5
DC109       9
dtype: int64

In [77]:
encoded_df_train.nunique()

DC216      15
DC220      84
DC142a    362
DC024      34
DC025       2
DC205       6
DC206       2
DC207       2
DC208       2
DC209       2
DC210       2
DC211       2
DC212       2
DC213      10
DC214      15
DC215      12
DC217       6
DC219       2
DC226      11
DC230a      5
DC230b      2
DC232       2
DC232b      2
DC235       3
DC237       3
DC237a      3
DC237b      3
DC237c      3
DC237d      3
DC237e      3
DC237f      3
DC241       4
DC242       2
DC244       2
DC246       2
DC252       5
DC270a      5
DC109       9
dtype: int64

In [78]:
df_test = pd.read_csv('../datasets/test.csv')
df_test.head()

id  DC024  DC025  DC205  DC206  DC207  DC208  DC209  DC210  DC211  ...   
0  26718     35      2     17      1      0      1      0      1      1  ...  \
1  26802     35      1     12      1      1      1      1      0      1  ...   
2  41302     74      2     12      1      0      1      1      1      1  ...   
3  38698     72      1     12      1      1      0      0      0      0  ...   
4  44257     76      2     12      1      0      1      0      0      1  ...   

   DC237e  DC237f  DC241  DC242  DC244  DC246  DC252  DC270a  DC109  DC142a  
0       0       0      1      1      1      1      1       3     21      52  
1       0       0      1      1      0      0      1       2     11      18  
2       0       0      1      0      0      1      4       5     11      78  
3       0       0      1      0      1      0      0       1     11      20  
4       0       0      1      1      1      1      1       3     11     125  

[5 rows x 39 columns]

In [79]:
test_id = df_test.pop('id')
df_test = df_test.astype(float)
df_test[CATEGORICAL_DATA] = df_test[CATEGORICAL_DATA].astype('category')

In [80]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
# scaler = StandardScaler()

numerical_df = df_test[NUMERICAL_DATA].copy()
categorical_df = df_test[CATEGORICAL_DATA].copy()

ohe_df = categorical_df

merged_df_test = pd.concat([numerical_df, categorical_df], axis=1)
X_test_submit = np.array(merged_df_test)

merged_df_test

DC216  DC220  DC142a DC024 DC025 DC205 DC206 DC207 DC208 DC209  ...   
0        1.0   29.0    52.0  35.0   2.0  17.0   1.0   0.0   1.0   0.0  ...  \
1        1.0   42.0    18.0  35.0   1.0  12.0   1.0   1.0   1.0   1.0  ...   
2        2.0   46.0    78.0  74.0   2.0  12.0   1.0   0.0   1.0   1.0  ...   
3        1.0   46.0    20.0  72.0   1.0  12.0   1.0   1.0   0.0   0.0  ...   
4        3.0   47.0   125.0  76.0   2.0  12.0   1.0   0.0   1.0   0.0  ...   
...      ...    ...     ...   ...   ...   ...   ...   ...   ...   ...  ...   
11985    2.0   36.0    70.0  65.0   2.0  12.0   1.0   0.0   1.0   0.0  ...   
11986    2.0   43.0   120.0  61.0   2.0  12.0   1.0   0.0   1.0   1.0  ...   
11987    2.0   45.0    72.0  74.0   1.0  12.0   1.0   1.0   1.0   1.0  ...   
11988    1.0   20.0     9.0  74.0   2.0  31.0   0.0   0.0   0.0   0.0  ...   
11989    3.0   52.0    96.0  81.0   1.0  12.0   1.0   0.0   1.0   1.0  ...   

      DC237d DC237e DC237f DC241 DC242 DC244 DC246 DC252 DC270a DC109  
0        0.0    0.0    0.0   1.0   1.0   1.0   1.0   1.0    3.0  21.0  
1        0.0    0.0    0.0   1.0   1.0   0.0   0.0   1.0    2.0  11.0  
2        0.0    0.0    0.0   1.0   0.0   0.0   1.0   4.0    5.0  11.0  
3        0.0    0.0    0.0   1.0   0.0   1.0   0.0   0.0    1.0  11.0  
4        0.0    0.0    0.0   1.0   1.0   1.0   1.0   1.0    3.0  11.0  
...      ...    ...    ...   ...   ...   ...   ...   ...    ...   ...  
11985    0.0    0.0    0.0   1.0   0.0   0.0   0.0   0.0    4.0  11.0  
11986    0.0    0.0    1.0   1.0   1.0   1.0   0.0   0.0    4.0  11.0  
11987    0.0    0.0    0.0   1.0   1.0   0.0   0.0   1.0    2.0  11.0  
11988    0.0    0.0    0.0   1.0   0.0   0.0   1.0   1.0    1.0  51.0  
11989    0.0    0.0    0.0   1.0   1.0   0.0   0.0   1.0    2.0  11.0  

[11990 rows x 38 columns]

In [81]:
encoded_df_test = encoder.transform(merged_df_test)
encoded_df_test

DC216  DC220  DC142a  DC024  DC025  DC205  DC206  DC207  DC208  DC209   
0        1.0   29.0    52.0     15      1      5      1      1      1      1  \
1        1.0   42.0    18.0     15      2      3      1      2      1      2   
2        2.0   46.0    78.0     28      1      3      1      1      1      2   
3        1.0   46.0    20.0     26      2      3      1      2      2      1   
4        3.0   47.0   125.0     30      1      3      1      1      1      1   
...      ...    ...     ...    ...    ...    ...    ...    ...    ...    ...   
11985    2.0   36.0    70.0     24      1      3      1      1      1      1   
11986    2.0   43.0   120.0     20      1      3      1      1      1      2   
11987    2.0   45.0    72.0     28      2      3      1      2      1      2   
11988    1.0   20.0     9.0     28      1      2      2      1      2      1   
11989    3.0   52.0    96.0     31      2      3      1      1      1      2   

       ...  DC237d  DC237e  DC237f  DC241  DC242  DC244  DC246  DC252  DC270a   
0      ...       1       1       1      1      2      2      2      2       5  \
1      ...       1       1       1      1      2      1      1      2       2   
2      ...       1       1       1      1      1      1      2      5       4   
3      ...       1       1       1      1      1      2      1      3       1   
4      ...       1       1       1      1      2      2      2      2       5   
...    ...     ...     ...     ...    ...    ...    ...    ...    ...     ...   
11985  ...       1       1       1      1      1      1      1      3       3   
11986  ...       1       1       2      1      2      2      1      3       3   
11987  ...       1       1       1      1      2      1      1      2       2   
11988  ...       1       1       1      1      1      1      2      2       1   
11989  ...       1       1       1      1      2      1      1      2       2   

       DC109  
0          6  
1          3  
2          3  
3          3  
4          3  
...      ...  
11985      3  
11986      3  
11987      3  
11988      7  
11989      3  

[11990 rows x 38 columns]

In [82]:
encoded_df_test['DC024'].unique()

array([15, 28, 26, 30,  2, 27,  3, 32, 31, 12,  5,  8, 14, 19, 11, 13,  7,
       33, 16,  1, 18, 25, 34, 23,  9,  4, 10, 17, 22, 21,  6, 24, 20, 29])

In [83]:
merged_df_test.nunique()

DC216      14
DC220      82
DC142a    283
DC024      34
DC025       2
DC205       6
DC206       2
DC207       2
DC208       2
DC209       2
DC210       2
DC211       2
DC212       2
DC213      11
DC214      16
DC215      12
DC217       6
DC219       2
DC226       9
DC230a      2
DC230b      2
DC232       2
DC232b      2
DC235       3
DC237       3
DC237a      3
DC237b      3
DC237c      3
DC237d      3
DC237e      3
DC237f      3
DC241       1
DC242       2
DC244       2
DC246       2
DC252       5
DC270a      5
DC109       9
dtype: int64

In [84]:
encoded_df_test.nunique()

DC216      14
DC220      82
DC142a    283
DC024      34
DC025       2
DC205       6
DC206       2
DC207       2
DC208       2
DC209       2
DC210       2
DC211       2
DC212       2
DC213      11
DC214      16
DC215      12
DC217       6
DC219       2
DC226       9
DC230a      2
DC230b      2
DC232       2
DC232b      2
DC235       3
DC237       3
DC237a      3
DC237b      3
DC237c      3
DC237d      3
DC237e      3
DC237f      3
DC241       1
DC242       2
DC244       2
DC246       2
DC252       5
DC270a      5
DC109       9
dtype: int64

In [85]:
for column in CATEGORICAL_DATA:
    print(column)
    a = encoded_df_train[column].unique()
    b = encoded_df_test[column].unique()
    print(a, '|', b)
    non_unique = np.setdiff1d(b,a)
    print(non_unique)
    print('---')

DC024
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34] | [15 28 26 30  2 27  3 32 31 12  5  8 14 19 11 13  7 33 16  1 18 25 34 23
  9  4 10 17 22 21  6 24 20 29]
[]
---
DC025
[1 2] | [1 2]
[]
---
DC205
[1 2 3 4 5 6] | [5 3 2 1 4 6]
[]
---
DC206
[1 2] | [1 2]
[]
---
DC207
[1 2] | [1 2]
[]
---
DC208
[1 2] | [1 2]
[]
---
DC209
[1 2] | [1 2]
[]
---
DC210
[1 2] | [2 1]
[]
---
DC211
[1 2] | [2 1]
[]
---
DC212
[1 2] | [1 2]
[]
---
DC213
[ 1  2  3  4  5  6  7  8  9 10] | [ 3.  1.  5.  7.  2.  4.  9.  6.  8. 10. -1.]
[-1.]
---
DC214
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] | [ 2.  1.  3.  8.  4.  7.  6. 13. 12. 14.  9.  5. 11. 10. -1. 15.]
[-1.]
---
DC215
[ 1  2  3  4  5  6  7  8  9 10 11 12] | [ 5  1  6  3  2  4  9 12  8 11  7 10]
[]
---
DC217
[1 2 3 4 5 6] | [3 2 1 4 5 6]
[]
---
DC219
[1 2] | [2 1]
[]
---
DC226
[ 1  2  3  4  5  6  7  8  9 10 11] | [ 2  4  1  3  7  9 11 10  6]
[]
---
DC230a
[1 2 3 4 5] | [1 2]
[]
---
DC230b
[1 2] | 

In [99]:
# np.sort(merged_df_train['DC213'].unique())
np.sort(merged_df_train['DC214'].unique())

array([12., 21., 22., 23., 24., 25., 26., 31., 32., 34., 35., 36., 37.,
       38., 96.])

In [98]:
# np.sort(merged_df_test['DC213'].unique())
np.sort(merged_df_test['DC214'].unique())

array([12., 13., 21., 22., 23., 24., 25., 26., 31., 32., 34., 35., 36.,
       37., 38., 96.])

In [100]:
# a = merged_df_train['DC213'].unique()
a = merged_df_train['DC214'].unique()
# b = merged_df_test['DC213'].unique()
b = merged_df_test['DC214'].unique()
print(a, '|', b)
non_unique = np.setdiff1d(b,a)
print(non_unique)

[36.0, 35.0, 23.0, 32.0, 24.0, ..., 21.0, 26.0, 37.0, 96.0, 25.0]
Length: 15
Categories (15, float64): [12.0, 21.0, 22.0, 23.0, ..., 36.0, 37.0, 38.0, 96.0] | [35.0, 36.0, 23.0, 34.0, 32.0, ..., 24.0, 21.0, 22.0, 13.0, 25.0]
Length: 16
Categories (16, float64): [12.0, 13.0, 21.0, 22.0, ..., 36.0, 37.0, 38.0, 96.0]
[13.]


In [102]:
# unknown_test_data = merged_df_test[merged_df_test['DC213'] == 12]
unknown_test_data = merged_df_test[merged_df_test['DC214'] == 13]
unknown_test_data

DC216  DC220  DC142a DC024 DC025 DC205 DC206 DC207 DC208 DC209  ...   
5299    1.0   52.0    30.0  53.0   2.0  31.0   0.0   0.0   0.0   0.0  ...  \

     DC237d DC237e DC237f DC241 DC242 DC244 DC246 DC252 DC270a DC109  
5299    0.0    0.0    0.0   1.0   1.0   1.0   1.0   1.0    1.0  51.0  

[1 rows x 38 columns]

In [ ]:
unknown_test_data = merged_df_test[merged_df_test['DC214'] == 12]
unknown_test_data

In [88]:
np.sort(encoded_df_test['DC024'].unique())

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [89]:
mask = encoded_df_test.isna().any(axis=1)
encoded_df_test[mask]

Empty DataFrame
Columns: [DC216, DC220, DC142a, DC024, DC025, DC205, DC206, DC207, DC208, DC209, DC210, DC211, DC212, DC213, DC214, DC215, DC217, DC219, DC226, DC230a, DC230b, DC232, DC232b, DC235, DC237, DC237a, DC237b, DC237c, DC237d, DC237e, DC237f, DC241, DC242, DC244, DC246, DC252, DC270a, DC109]
Index: []

[0 rows x 38 columns]

In [90]:
df['DC216'].unique()


array([ 1.,  2.,  3.,  4., 10.,  0.,  5.,  6.,  7.,  8., 20.,  9., 12.,
       11., 14.])